apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: akasha-rag
  name: akasha-rag
  namespace: akasha
spec:
  selector:
    matchLabels:
      app: akasha-rag
  template:
    metadata:
      labels:
        app: akasha-rag
    spec:
      containers:
        - name: akasha-rag
          image: akasha_dev_ui:latest # Change this to the name of your image
          imagePullPolicy: IfNotPresent
          args: []
          env: 
            - name: PREFIX
              value: akasha-dev # Change this to the path you want to serve your app at
          ports:
            - containerPort: 8501
          resources:
            limits:
              cpu: 8000m
              memory: 16Gi
            requests:
              cpu: 4000m
              memory: 4Gi
          volumeMounts:
          - name: model-volume
            mountPath: /app/model
          - name: config-volume
            mountPath: /app/config
          - name: docs-volume
            mountPath: /app/docs
          - name: chromadb-volume
            mountPath: /app/chromadb
          - name: account-volume
            mountPath: /app/accounts.yaml
            subPath: accounts.yaml
      volumes:
        - name: model-volume
          persistentVolumeClaim:
            claimName: akasha-model-pvc
        - name: config-volume
          persistentVolumeClaim:
            claimName: akasha-config-pvc
        - name: docs-volume
          persistentVolumeClaim:
            claimName: akasha-docs-pvc
        - name: chromadb-volume
          persistentVolumeClaim:
            claimName: akasha-chromadb-pvc
        - name: account-volume
          persistentVolumeClaim:
            claimName: akasha-account-pvc
      restartPolicy: Always
